language: rust
rust:
  - nightly-2020-12-31
sudo: false
cache: cargo

before_script:
- rustup component add rustfmt
- rustup target add wasm32-unknown-unknown
script:
  - cargo fmt --all -- --check
  - bash ./.travis.build.sh

