[package]
name = "oep8token"
version = "0.1.0"
authors = ["lucas7788 <sishsh@163.com>"]
edition = "2018"

[dependencies]
ontio-std = {path="../../ontio-std"}
rust-base58 = "0.0.4"

[features]
mock = ["ontio-std/mock"]
