[package]
name = "oep5token-codegen"
version = "0.1.0"
authors = ["lucas7788 <sishsh@163.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ontio-std = {path="../../ontio-std"}
rust-crypto-wasm = "0.3.1"

[features]
mock = ["ontio-std/mock"]
